### ISSUE TITLE
Can l play it without saving it?

### ISSUE THREAD

**Issue by HybridDog** [mydzor/bash2048#21]
It doesn't work using
```curl -s https://raw.githubusercontent.com/mydzor/bash2048/master/bash2048.sh | bash```
or
```curl -s https://raw.githubusercontent.com/mydzor/bash2048/master/bash2048.sh | sponge | bash```

**Comment by dacamp** [comment]
This is what you're looking for.

```lang=bash
$ bash <(curl -s https://raw.githubusercontent.com/mydzor/bash2048/master/bash2048.sh)
```

**Comment by HybridDog** [comment]
thanks
