### ISSUE TITLE
Don't directly close the terminal

### ISSUE THREAD

**Issue by wyz23x2** [mydzor/bash2048#30]
In Ubuntu, when the target is reached or there are no moves, the terminal just exits. There's not time to look at the text echoed!

**Comment by wyz23x2** [comment]
P.S. closes when running by ``source``.

**Comment by mydzor** [comment]
that is expected, if you start the game with 
`source bash2048.sh` or `. bash2048.sh`, you are replacing current shell with the game, so once the game closes there is no shell to go back to and your terminal window closes, please either and run it directly:
`./bash2048.sh` or run it in a new shell `bash bash24048.sh`
